### PR TITLE
Fix linter issues

### PR DESCRIPTION
**Pull request by mrigorir**
Complete The project.

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 
Hello, @mrigorir great work on this project, and good work making the changes as requested. Also, great work on your project. It is well-aligned 👏🏿 . However, there are a few changes to be made kindly check below ⬇️ 

- [ ] You have not included the suggested newsletter section, more in space astronomy and Editors pick. Kindly remember all the sections from the original website should be included. Kindly check below ⬇️ 

Screenshot from 2021-02-18 10-06-01

Use this [link](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) to see the original website. 

- [ ] Your pull request message should be descriptive. Kindly remember it should have a title and short description explaining what you have worked on.
descriptive_prs

[link to pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

- [ ] Kindly don't close your pull-request once a review is done. Use the same pull-request until the project is approved.


### if you have a question concerning the review, kindly reach me on slack @peterrobert


### HAPPY CODING 💻

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Marco Parra Leal** 
Good job with the improvements for this project :muscle:  :muscle:
Most of your page looks like the original :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Add the link the the Live Demo in your README file
- [ ] There most be a Editor's pick section upon the footer:

| Yours | Original |
|:---:|:---:|
|image | image |
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by mrigorir** [comment]
Hello Oscar!

Sorry i don't understand. I already have made the editors pick. How is that
it does not showing?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mrigorir** [comment]
Here:
https://github.com/mrigorir/NYT-article/pull/5/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051


in the index.html, you can see on green I have added a newsletter section.
(editor's pick)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Review by wathigo — CHANGES_REQUESTED** [review]
### REQUIRES CHANGES :o: 
Great job implementing the suggested changes.
However, some issues still need to be addressed

#### REQUIRED
**Bottom Part**
* We have a very big margin caused by the height of the most popular section. We can do this by increasing the width of the section or by reducing/using a different fonts. See this :point_down: 

Clone Version | Original Version
|------------------:|:---------------------|
Screenshot from 2021-02-18 19-46-16 | original_editor_bottom

**After making the changes, submit another request for review.**

**Happy Learning :technologist: 
Simon Wathigo**

**Comment by mrigorir** [comment]
Hello.

Sorry, but I don't understand what's happening. In my local project, it
does not look like that. It all looks bigger in the demo than it truly is.

 If I open the demo in another browser, it doesn't look like it is shown in
chrome.

 Can you tell me please what's going on?

I do not have a huge margin in my code witch separates the sections that
way.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mrigorir** [comment]
Finish the project with all corresponding sections and indications from the code reviewers. 

Fix a problem with the browser rendering page.

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
